### ISSUE TITLE
破坏华尔街日报

### ISSUE THREAD

**Issue by ivysrono** [eight04/linkify-plus-plus#12]
https://wallstreetcn.com/articles/3359944
导致全页空白。

**Comment by eight04** [comment]
![image](https://user-images.githubusercontent.com/1324510/42915496-decd23f6-8b32-11e8-8698-fa6e186f7412.png)
我這正常。你的瀏覽器、Userscript Manager、LPP 的版本是？

**Comment by ivysrono** [comment]
Firefox 61.0.1 x64
[Violentmonkey 2.9.5](https://addons.mozilla.org/zh-CN/firefox/addon/violentmonkey/)
LPP 8.2.1
新建了个配置还是如此。

**Comment by eight04** [comment]
於 8.2.2 修正。
