### ISSUE TITLE
[Request] Offer as a webextension too?

### ISSUE THREAD

**Issue by FatOrangutan** [eight04/linkify-plus-plus#14]
The reason I ask is that I'm trying to migrate away from userscripts and towards extensions. The only linkifying webextension available for Firefox is [this one](https://addons.mozilla.org/en-US/firefox/addon/linkificator/) but it is slower than your script. So wondering if you have considered / are interested in releasing as a webextension too?

**Comment by eight04** [comment]
It should be easy to port the core part (URL matcher and the linkifier) to webextensions. The main missing feature is that we need a configuration system that supports different settings on different domains. Ideally, this config library should replace [GM_config](https://github.com/eight04/GM_config) entirely.

**Comment by eight04** [comment]
https://addons.mozilla.org/firefox/addon/linkify-plus-plus/

**Comment by JayBrown** [comment]
In macOS 11, Safari will again be open for browser extensions, easily portable, they say.
