### ISSUE TITLE
[Webextension] Ability to blacklist domains

### ISSUE THREAD

**Issue by FatOrangutan** [eight04/linkify-plus-plus#18]
While in the userscript version, this could be handled by the user includes/excludes feature of the *monkey extension itself, I couldn't find a way to fully disable the extension on some domains. I tried adding `*` in the `Do not linkify following elements` for those domains but it didn't seem to work.

Edit: I mostly want to disable it on `google.*`, which was an `@exclude` of the userscript but apparently not excluded in the webextension version.

**Comment by eight04** [comment]
You can set `Do not linkify following elements` to `body` so that all elements would be excluded and the linkifier would never run.

**Comment by FatOrangutan** [comment]
Ah ok, that works. Thanks!
