### ISSUE TITLE
Doesn't work at battle.net

### ISSUE THREAD

**Issue by Iowerth** [eight04/linkify-plus-plus#19]
Hi.
It doesn't work on battle.net.
For example check https://us.battle.net/forums/en/wow/topic/20761937777#post-5
Screenshot is here - http://i.imgur.com/6XQrhhC.png

**Comment by eight04** [comment]
We have to add the content type `application/xhtml+xml`.
https://github.com/eight04/linkify-plus-plus/blob/c9e4992c526ee3ad666ed84fb8c790952ca41b9f/src/lib/main.js#L190-L197

**Comment by Iowerth** [comment]
> We have to add the content type `application/xhtml+xml`.
When it will be added?

**Comment by eight04** [comment]
Probably next week.
