### ISSUE TITLE
Need more detailed help message

### ISSUE THREAD

**Issue by eight04** [eight04/linkify-plus-plus#21]
> 
> Domain: I would display this above a the domain selection 
> 
> Match IP with only 4 digits:  what IP ? which 4 digits?  
> 
> Embed images: what does it mean ?
> 
> Exclude following elements, (CSS selector):  what can I write here
> .hljs, .highlight, .brush\: : what happens if I delete this  accidentally, how can I restore?
> 
> Similar questions for "Do not linkify elements" and "Always  linkify elements"
> 
> Max "executation"  typo, execution . I think I understand.
> 
> Max script run time: what script? 
> 
> How can I "split the process"
> 
> Custom rules : what they rule?

**Comment by ankostis** [comment]
Please, also provide some screenshots in action.
