### ISSUE TITLE
Broken on raw returned JSON?

### ISSUE THREAD

**Issue by MichaelMai2000** [eight04/linkify-plus-plus#26]
Cannot detect link in raw returned JSON?
https://api.scryfall.com/cards/ed2e3b59-ddbe-4e82-ad67-dd21302a31cb
or
https://api.scryfall.com/cards/ed2e3b59-ddbe-4e82-ad67-dd21302a31cb?format=json&pretty=true

**Comment by eight04** [comment]
Browser version? In Firefox it looks like:
![image](https://user-images.githubusercontent.com/1324510/79683903-f1e45b00-825f-11ea-9cd7-37079bb8672f.png)

**Comment by MichaelMai2000** [comment]
Chrome 81.0.4044.113

**Comment by MichaelMai2000** [comment]
> Browser version? In Firefox it looks like:
> ![image](https://user-images.githubusercontent.com/1324510/79683903-f1e45b00-825f-11ea-9cd7-37079bb8672f.png)

And yes, it works on Firefox.

It seems that Firefox is able to detect JSON as a specified return type rather than raw?

Chrome and Firefox give different outcomes.

**Comment by MichaelMai2000** [comment]
Further experiment shows that Firefox can detect JSON even WITHOUT the Linkify Plus Plus extension, lol......

**Comment by eight04** [comment]
I suggest installing a JSON viewer extension so you can get more powerful features like Firefox. Currently, the script doesn't run on JSON pages.
https://github.com/eight04/linkify-plus-plus/blob/30af757edeb946a588fd101f2ad6546a8130323e/src/shared/main.js#L204
