### ISSUE TITLE
Can't detect link from texts

### ISSUE THREAD

**Issue by Cyberavater** [eight04/linkify-plus-plus#27]
Eglink: https://paste2.org/0xZzVVek

**Comment by eight04** [comment]
![image](https://user-images.githubusercontent.com/1324510/82181503-3aea0680-9915-11ea-9478-362ab9504b5c.png)

The script ignore highlighted code by default. To linkify them, remove `.highlight` from `Do not linkify following elements.` option.

**Comment by Cyberavater** [comment]
Nice, thanks! BTW, can you make it 'tick & untick' option rather than 'adding and removing' option?

**Comment by eight04** [comment]
Listing all possible selectors can be a problem here. Using a textarea makes it easier to add your own CSS selectors.
