### ISSUE TITLE
Problems linkifying the macupdater URI

### ISSUE THREAD

**Issue by JayBrown** [eight04/linkify-plus-plus#28]
On macOS there is the **macupdater** URI scheme… see e.g. "Install App via MacUpdater" here: https://macupdater.net/app_updates/appinfo/com.busymac.busycal3/index.html … the custom URL used there is: macupdater://com.busymac.busycal3

So I tried to linkify`macupdater://` URLs in Firefox with `macupdater://\S+` in the custom rules, but it doesn't work.

However, with other URI schemes, it's working fine, e.g. **macappstore** with `macappstore://\S+`, and even with a simple test scheme like **uplc** with `uplc://\S+`.

MAS: macappstore://ax.search.itunes.apple.com/WebObjects/MZSearch.woa/wa/search?q=pixelmator
Test: uplc://cGwyMDIwMDYyMzE0MjYzMC50YXI=.0.7837a05d73f49de13276b8455f94d85be7d646cbaa05477ee6135c0542fbabab.0b87c36b2ce9f27abd95e5d5e9c89092617f4167ad36a74b9aca6138621d413b.dXBsLTIwMjAwNjIzXzE0MjYzMC50YXI=.104448

These two work, but not the `macupdater` URI. What am I doing wrong?

**Comment by eight04** [comment]
Hmm. I think it is a bug in the url matcher. `macupdater://com.busymac.busycal3` matches the URL regular expression. However, it is considered invalid and skipped.

Maybe we shouldn't skip those *invalid* URLs if it has an unknown protocol. It should be safe to assume it is a useable URL as long as we can detect the protocol part.
