### ISSUE TITLE
Deactivate after detecting a certain amount of URLs on a page

### ISSUE THREAD

**Issue by reddit-is-fun** [eight04/linkify-plus-plus#3]
Linkify Plus Plus currently causes my browser to crash on pages that have a large number of URLs, for example: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts

In my opinion there should be an option to automatically deactivate the script when a certain amount of URLs, for example 100, are detected on one page. This is also a security issue on websites that list malicious domains, the links shouldn't be turned into hyperlinks.

**Comment by eight04** [comment]
I can't reproduce it. Which browser do you use?

Currently LPP will stop if it spends more than 10 seconds (configurable) in one search.

To prevent the access to the malicious websites, you need an antivirus or some addons like uBlock Origin.

**Comment by reddit-is-fun** [comment]
> Which browser do you use?

Firefox.

> Currently LPP will stop if it spends more than 10 seconds (configurable) in one search.

I'm aware of that, but I'd prefer to set a limit of hyperlinks instead. Turning thousands of plain URLs into hyperlinks on one page is by no means necessary.

**Comment by eight04** [comment]
Which version of Firefox? Did you enable e10s?

> set a limit of number of hyperlinks

How about [this file](https://gist.githubusercontent.com/eight04/44cce809f3716ff49fbffb15ac7637fd/raw/1e5e972c2e6c9fdec9e5042d3c4d090343022e92/hosts)? I have replaced "." with "-" so there are no URLs. Does the browser crash with it?

**Comment by reddit-is-fun** [comment]
> Which version of Firefox? Did you enable e10s?
The latest version, currently 45.0.1. I've tested on Windows 10 and a couple of Linux distros.

> How about this file? I have replaced "." with "-" so there are no URLs. Does the browser crash with it?
Doesn't cause crash, to page loads fine. My browser generally crashes on pages that have a lot of (maybe over 1000) URLs when Linkify is enabled.

I've installed Linkify Plus Plus from here: https://greasyfork.org/en/scripts/4255-linkify-plus-plus

**Comment by eight04** [comment]
Windows 7 64bit
Firefox 45.0.1 32bit and 64bit
Greasemonkey 3.7
Linkify Plus Plus 7.2.0
![http://i.imgur.com/tRwtpJa.png](http://i.imgur.com/tRwtpJa.png)
Can't reproduce it.

Did you try to test in a new profile? Maybe it is conflict with some other scripts or addons.

**Comment by reddit-is-fun** [comment]
No longer seems to happen, I started with a fresh profile using the same addons.  
I can't stress enough that there should be a some sort of limit in place by default, I think it is unnecessary to add hyperlinks to 500 000 plain URLs on one page.

**Comment by eight04** [comment]
What kind of webpage which contains 500000 URLs? For the host file, you may want to add some excluding rule like `http*/hosts` to your script setting.

**Comment by reddit-is-fun** [comment]
I was exaggerating, but it's clear that you don't want to support this feature and it's time for me to learn userscript development.

**Comment by eight04** [comment]
If we can confirm that this issue is caused by the amount of the links, I would be willing to add this feature.
