### ISSUE TITLE
Won't linkify links starting with a -

### ISSUE THREAD

**Issue by MoneyAllDay** [eight04/linkify-plus-plus#34]
Why won't it linkify the links that have a - before the link?

The links are at the end of the page.
[Torrentfreak link](https://torrentfreak.com/u-s-governments-list-of-notorious-piracy-markets-is-a-mixed-bag-210119/)

**Comment by eight04** [comment]
This is similar to #28. The URL matches the regexp but then is considered invalid since the domain starts with `-`.
