### ISSUE TITLE
Error on Brave Browser

### ISSUE THREAD

**Issue by Marcosdw** [eight04/linkify-plus-plus#35]
Hello,

Brave Browser errors:

Unrecognized manifest key 'applications'.
 "applications": {
    "gecko": {
      "strict_min_version": "52.0"
    }
  }
Unrecognized manifest key 'developer'.
 "developer": {
    "name": "eight04",
    "url": "https://github.com/eight04"
  },

Please fix, thank's

**Comment by eight04** [comment]
Chromium-based browsers don't support `applications` and `developer` metadata. It doesn't affect functionality so you can safely ignore them.

**Comment by Marcosdw** [comment]
OK Thank's
