### ISSUE TITLE
Linkify domains starting with numbers

### ISSUE THREAD

**Issue by bolach** [eight04/linkify-plus-plus#37]
Hello
I cant install on chrome. When i load the folder it says:
Could not load manifest.

https://i.imgur.com/YANOara.png

Anyone has one idea how to solve it?

**Comment by eight04** [comment]
Oops. I have changed how the extension is built in latest master (#33) but I didn't update the README. In the future, you will be able to download the extension in the [releases](https://github.com/eight04/linkify-plus-plus/releases) page. Currently, you can try the userscript version:
https://github.com/eight04/linkify-plus-plus/raw/master/dist/linkify-plus-plus.user.js

If you need an extension zip instead, reply and I will build one and put it here.

**Comment by bolach** [comment]
Thanks, i was abble to install

But it seems that doesnt work with one sepecific link type with bbcode
Inside [code] test [/code] i can have all links clickable, except from 1fichier :s

https://i.imgur.com/FOwmERk.png

**Comment by eight04** [comment]
I incorrectly implemented the old validator that doesn't allow numbers as the first char:
https://serverfault.com/questions/638260/is-it-valid-for-a-hostname-to-start-with-a-digit

**Comment by bolach** [comment]
I was reading that page, but i really dont understood what happen and i think that there is no fix for this situation
Hope one day you can fix this :)
