### ISSUE TITLE
Bug: for Custom protocol rules 

### ISSUE THREAD

**Issue by dnknn** [eight04/linkify-plus-plus#39]
> [This script](https://greasyfork.org/scripts/4255) is very good, thank you very much for providing this powerful link tool! report a problem below : 

## Custom protocol rules

<details><summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/111054535-70fe0580-84a8-11eb-942a-74ecbab7f05e.png)</details>  

`(chrome|about|chrome-extension):(//)?([\w\-?.=]+)(/[^\s"]*)?`

or

`ms-settings:(//)?([\w-]+)?|ms-windows-store:(//)?([\w-\/?]+)?(=[^\s"]+)?`

Obviously, there is no problem with the `RegExp` itself, right!

---

# Test

when use the above Custom protocol rules , the following example link  will not work

　
- 👉 https:greasyfork.org/scripts/4255/ 👈

　
When I remove the above Custom protocol rules, it will work normally....

More test

chrome://settings/system
chrome-extension:dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=utils
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=utils
chrome:dino
about:dino
ms-settings:yourinfo

---

So I can’t explain this behavior myself, I can only attribute it to the bug ....

**Comment by dnknn** [comment]
I have repeatedly checked and tested, and found that it seems to be related to the question mark `❓` of the RegExp.

**Comment by eight04** [comment]
Hmm since custom rules are parsed first, capture groups affect match index.

Before the bug is fixed, try to use non-capturing group e.g.
```
(?:chrome|about|chrome-extension):(?://)?[\w\-?.=]+(?:/[^\s"]*)?
```

**Comment by dnknn** [comment]
> ```
> (?:chrome|about|chrome-extension):(?://)?[\w\-?.=]+(?:/[^\s"]*)?
> ```

Thank you very much, the non-capturing group can work perfectly
