### ISSUE TITLE
possibly not working in some cases

### ISSUE THREAD

**Issue by atomGit** [eight04/linkify-plus-plus#4]
firefox, linux, LPP 7.3.0

links here in the code comments (// ... ) are not being linkified...

https://github.com/pyllyukko/user.js/blob/master/user.js

the links in your test cases are however

**Comment by eight04** [comment]
Linkifying on code is disabled by default. If you want to make it work on all code, remove `.highlight` selector from excluding list, but it might linkify a bunch of identifier containing `.`.

Another way is to add `.pl-c` selector to including list, so it will linkify all URLs inside a comment.

**Comment by atomGit** [comment]
ah, got it - i should have paid more attention to the css selectors in the prefs - thanks!
