### ISSUE TITLE
Problem with the setting "Always linkify following elements. Override above. (CSS selector)"

### ISSUE THREAD

**Issue by decembre** [eight04/linkify-plus-plus#41]
If i add a slector in "Always linkify following elements. Override above. (CSS selector)",
and after i want delete totally it, it is not possible.
The form don't want be empty.
I need to let in it something which match noting to make it save it.
If i try to save an empty form, it return to the previous value typed in it.

It's why i understang many errors this last:
I have found it was due to this setting, i correct it and after ....  i don't understand why these problems remain:
now i known why;
:-)

**Comment by eight04** [comment]
Good catch. Currently the validator doesn't allow empty string:
https://github.com/eight04/linkify-plus-plus/blob/c79fc8232cb3997de429b1422d7ec6741dbc9100/src/lib/pref-body.js#L89-L91
