### ISSUE TITLE
break https://101weiqi.com/guan/

### ISSUE THREAD

**Issue by ivysrono** [eight04/linkify-plus-plus#42]
![图片](https://user-images.githubusercontent.com/2649544/118829494-c0b9dc80-b8f0-11eb-80a3-a26b92f313d5.png)
It shoud be ：
![图片](https://user-images.githubusercontent.com/2649544/118829661-e0e99b80-b8f0-11eb-912e-c0133abccbe2.png)

**Comment by eight04** [comment]
It seems that the page uses Angular 1.x with different interpolate symbols:
https://static2.101weiqi.com/static/cache/cba02fa84e9fae2a02c46837ae606d29.js
```js
wqapp.config(["$interpolateProvider",function(e){e.startSymbol("[["),e.endSymbol("]]")}])
```
I think this issue is an edge case. You may exclude the page in the script manager.

**Comment by ivysrono** [comment]
> You may exclude the page in the script manager.

It's hard in mobile firefox.

**Comment by ivysrono** [comment]
Or any other script can fix it?

**Comment by eight04** [comment]
> > You may exclude the page in the script manager.
> 
> It's hard in mobile firefox.

Another option is to exclude `[ng-app]` elements in script config. This will make the script skip all Angular 1.x apps.

> Or any other script can fix it?

I don't think so. 101weiqi has to pre-compile the template into a render function so it doesn't output the source template to the page. But I think there is no such feature in Angular 1.x.

**Comment by ivysrono** [comment]
https://www.101weiqi.com/q/14910/
