### ISSUE TITLE
Emoji is not supported

### ISSUE THREAD

**Issue by dnknn** [eight04/linkify-plus-plus#43]
[seeing here picture](https://user-images.githubusercontent.com/10995302/123339555-66f6a300-d57d-11eb-9a29-9a0001bb67ba.png) Obviously, it was truncated by mistake: 👇 Live demonstration case:
　
https://github.com/eight04/linkify-plus-plus#Features#:~:text=Support,images
`https://github.com/eight04/linkify-plus-plus#Features#:~:text=Support,images`
`https://github.com/eight04/linkify-plus-plus#Features#💡:~:text=Support,images`

```js
https://github.com/eight04/linkify-plus-plus#Features#:~:text=Support,images
https://github.com/eight04/linkify-plus-plus#Features#💡:~:text=Support,images
```

![216_25063121](https://user-images.githubusercontent.com/10995302/123340566-f781b300-d57e-11eb-9a03-3d52c95a26c2.png)

----------------------

- about `#:~:text=` API Documentation :	[`#:~:text=`](https://user-images.githubusercontent.com/10995302/123339555-66f6a300-d57d-11eb-9a29-9a0001bb67ba.png)
https://github.com/WICG/scroll-to-text-fragment
https://wicg.github.io/scroll-to-text-fragment/
https://web.dev/text-fragments/#text-fragments

- Link to Text Fragment (Google extension tool)
https://chrome.google.com/webstore/detail/pbcodcjpfjdpcineamnnmbkkmkdpajjg

**Comment by eight04** [comment]
Try enabling the option `Match unicode characters`.
