### ISSUE TITLE
Linkify Plus Plus on Brave browser

### ISSUE THREAD

**Issue by Marcosdw** [eight04/linkify-plus-plus#51]
Hello,,
linkify plus plus 10 does not work in brave browser:  [Version 1.38.27 Chromium: 99.0.4844.51]
I followed the instructions https://github.com/eight04/linkify-plus-plus#chrome-extension
Linkify does not appear in extensions
Greetings
Marco

---
Sorry I use an online translator French English

**Comment by eight04** [comment]
![image](https://user-images.githubusercontent.com/1324510/158143088-b11cdf88-7e57-4ff5-be5f-fb56aefa15fe.png)

I can't reproduce with Brave V1.36.112 (Mar 10, 2022). Can you post some screenshots of how you installed the extension?

**Comment by Marcosdw** [comment]
Work fine now ;)
But error reported, look at the screenshot
![Capture d’écran 2022-03-14 190324](https://user-images.githubusercontent.com/18121470/158234301-277e0979-a0f6-4aa0-a806-6128da7cd5ac.png)

**Comment by eight04** [comment]
👍 Those warnings don't affect functionality so you can ignore them.
