### ISSUE TITLE
Breaks accessibility when there is an email placeholder in a form

### ISSUE THREAD

**Issue by tomasforsman** [eight04/linkify-plus-plus#53]
When there is an email placeholder in a form it breaks the tab functionality of that form due to the mail adress being linkified. You can't overwrite the placeholder text by just start typing but instead have to deselect the link to overwrite it.

Example: The registration form at https://pages.jetbrains.com/dotnet-days-2022/blogpost

**Comment by eight04** [comment]
It seems that you can tab again to enter the email.

The site doesn't provide any information about that the address is a placeholder.
