### ISSUE TITLE
Soap2Day Videos Do NOT Play on Firefox When Linkify-Plus-Plus is Enabled

### ISSUE THREAD

**Issue by npn225** [eight04/linkify-plus-plus#54]
As stated in the title, this script breaks all videos on all mirrors for the Soap2Day on FireFox Browser

Expected Result when this script is enabled: Videos play normally
Actual Result when this script is enabled: Videos will never load or will just break

Operating System: Linux 
Browser: Firefox 
Script-Manager: TamperMonkey 
Site: https://soapgate.cc/

**Comment by eight04** [comment]
It seems that soap2day stores their server URL in a hidden div, which is linkified by the script.

Try adding the following CSS selector to your exclusion list:
```css
[style*="display:none"]
```

Maybe we can add an option to ignore hidden elements.

**Comment by npn225** [comment]
Hey @eight04, 

Thanks for replying!  

Unfortunately, adding that CSS selector does not fix the issue - I put it in both the User matches and User excludes!  

I guess I'll just keep disabling this script for this site!  

Thanks again!

**Comment by eight04** [comment]
Here is the correct field:
![image](https://user-images.githubusercontent.com/1324510/203149434-7e404517-4f8a-4962-9aea-dddd82800ad5.png)

Should we exclude soap2day by default? Have you seen any plain text URL on soap2day?

**Comment by npn225** [comment]
Hey @eight04,

I entered your CSS snippet into the correct field and it still doesn't work!  

Honestly, you probably should exclude soap2day by default seeing as there really isn't any plain text URL throughout the site that warrants the use of this script!  

Thanks again for being so communicative and helpful!

**Comment by eight04** [comment]
The latest version with mouse over trigger won't convert hidden content anymore.
