### ISSUE TITLE
Doesn't work on Firefox with Tampermonkey

### ISSUE THREAD

**Issue by Keith94** [eight04/linkify-plus-plus#7]
Script is active in Tampermonkey, but links on [this page](https://www.nyaa.se/?page=view&tid=876739#c602645) are not clickable.

Greasemonkey on Firefox works as expected.

**Comment by eight04** [comment]
This have been fixed in tampermonkey master but not reviewed by AMO yet. You can try the beta version first, see https://github.com/Tampermonkey/tampermonkey/issues/360#issuecomment-285495740.
