### ISSUE TITLE
Script breaks Huawei page

### ISSUE THREAD

**Issue by Morku** [eight04/linkify-plus-plus#9]
When you go to the page: http://consumer.huawei.com/en/
Click on Phones on the top left corner. -> See all Phones and try to select some attributes, it always says "Sorry, No results were found."
Disable linkify and it does work.
Tested with version 8.1.0, Tampermonkey 4.5.5553 and Firefox 56.0

**Comment by eight04** [comment]
They put their data in a hidden `<div>`. To fix it, you can add `[class^=data-]` to exclude selector.
